firstProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.ProductList.as_view()),
    path('<int:pk>/', views.ProductDetail.as_view()),
    path('create_product/', views.ProductCreate.as_view()),
    path('update_product/<int:pk>/', views.ProductUpdate.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('company/<str:slug>/', views.company_page),
    path('popular_items/', views.popular_items_page),
    path('tag/<str:slug>/', views.tag_page),
    path('new_arrivals/', views.new_items_page),
    path('about/', views.about_page),
]

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit, Thumbnail

# Create your models here.
class AdditionalFeature(models.Model):
  name = models.CharField(max_length=50, unique=True)
  slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

  def __str__(self):
    return self.name

class Tag(models.Model):
  name = models.CharField(max_length=50, unique=True)
  slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return f'/product/tag/{self.slug}/'

class Category(models.Model):
  name = models.CharField(max_length=50, unique=True)
  slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return f'/product/category/{self.slug}/'

  class Meta:
    verbose_name_plural = 'Categories'

class Company(models.Model):
  name = models.CharField(max_length=50, unique=True)
  slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
  address = models.CharField(max_length=70)
  contact = models.CharField(max_length=50, unique=True)
  company_image = models.ImageField(upload_to='product/company/images/%Y/%m/%d/', blank=True)
  description = models.CharField(max_length=255, blank=True)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return f'/product/company/{self.slug}/'

  class Meta:
    verbose_name_plural = 'Companies'

class Product(models.Model):
  title = models.CharField(max_length=80)
  hook_text = models.CharField(max_length=100, blank=True)
  description = models.TextField()
  date = models.DateField(default=timezone.now, editable=True)
  product_image = models.ImageField(upload_to='product/product/images//%Y/%m/%d/', blank=True)
  detail_image = models.ImageField(upload_to='product/product/images/%Y/%m/%d/', blank=True)
  product_price = models.IntegerField()
  on_sale_price = models.IntegerField(null=True, blank=True)
  rating = models.IntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])
  company = models.ForeignKey(Company, null=True, blank=True, on_delete=models.SET_NULL)
  category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
  tags = models.ManyToManyField(Tag, blank=True)
  additional_feature = models.ForeignKey(AdditionalFeature, null=True, blank=True, on_delete=models.SET_NULL)
  author = models.ForeignKey(User, default='admin', null=True, on_delete=models.SET_NULL)

  def __str__(self):
    return f'[{self.pk}] {self.title}:: {self.product_price} : {self.company}'

  def get_absolute_url(self):
    return f'/product/{self.pk}/'

product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Category, Company, Tag
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify

# Create your views here.
class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    fields = ['product_image', 'detail_image', 'title', 'hook_text', 'product_price',
              'on_sale_price', 'rating', 'company', 'additional_feature', 'category',
              'description']

    template_name = 'product/product_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(ProductUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(ProductUpdate, self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(';', ',')
            tags_list = tags_str.split(',')
            for new_tag in tags_list:
                new_tag = new_tag.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=new_tag)
                if is_tag_created:
                    tag.slug = slugify(tag, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()
            for tag in self.object.tags.all():
                tags_str_list.append(tag.name)
            context['tags_str_default'] = ';'.join(tags_str_list)
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Product.objects.filter(category=None).count
        return context

class ProductCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
  model = Product
  fields = ['date', 'product_image', 'detail_image', 'title', 'hook_text', 'product_price',
            'on_sale_price', 'rating', 'company', 'additional_feature', 'category',
            'description']

  def test_func(self):
      return self.request.user.is_superuser or self.request.user.is_staff

  def form_valid(self, form):
      current_user = self.request.user
      if current_user.is_authenticated and (current_user.is_superuser
                                            or current_user.is_staff):
          form.instance.author = current_user
          response = super(ProductCreate, self).form_valid(form)

          tags_str = self.request.POST.get('tags_str')
          if tags_str:
              tags_str = tags_str.strip()
              tags_str = tags_str.replace(';', ',')
              tags_list = tags_str.split(',')
              for new_tag in tags_list:
                  new_tag = new_tag.strip()
                  tag, is_tag_created = Tag.objects.get_or_create(name=new_tag)
                  if is_tag_created:
                      tag.slug = slugify(tag, allow_unicode=True)
                      tag.save()
                  self.object.tags.add(tag)
          return response
      else:
          return redirect('/product/')

  def get_context_data(self, *, object_list=None, **kwargs):
    context = super(ProductCreate, self).get_context_data()
    context['categories'] = Category.objects.all()
    context['no_category_post_count'] = Product.objects.filter(category=None).count()
    return context

class ProductDetail(DetailView):
  model = Product

  def get_context_data(self, **kwargs):
    context = super(ProductDetail, self).get_context_data()
    context['related_products'] = Product.objects.filter(category_id=self.object.category_id).order_by('-pk')[0:4]
    context['related_products_count'] = Product.objects.filter(category_id=self.object.category_id).count()-1
    context['categories'] = Category.objects.all()
    context['no_category_post_count'] = Product.objects.filter(category=None).count()
    context['companies'] = Company.objects.all()
    return context

class ProductList(ListView):
  model = Product

  def get_context_data(self, *, object_list=None, **kwargs):
    context = super(ProductList, self).get_context_data()
    context['categories'] = Category.objects.all()
    context['no_category_post_count'] = Product.objects.filter(category=None).count
    context['companies'] = Company.objects.all()
    return context

def about_page(request):
  return render(request, 'product/about.html', {
    'categories': Category.objects.all(),
    'no_category_post_count': Product.objects.filter(category=None).count(),
    'companies': Company.objects.all()
  })

def new_items_page(request):
  new_items = Product.objects.all().order_by('-pk')[0:4]
  return render(request, 'product/product_list.html', {
    'new_items': new_items,
    'categories': Category.objects.all(),
    'no_category_post_count': Product.objects.filter(category=None).count()
  })

def popular_items_page(request):
  popular_items = Product.objects.filter(rating=5).order_by('-pk')
  return render(request, 'product/product_list.html', {
    'popular_items': popular_items,
    'categories': Category.objects.all(),
    'no_category_post_count': Product.objects.filter(category=None).count(),
    'companies': Company.objects.all()
  })

def category_page(request, slug):
  if slug == 'no_category':
    category = 'etc'
    product_list = Product.objects.filter(category=None).order_by('-pk')
  else:
    category = Category.objects.get(slug=slug)
    product_list = Product.objects.filter(category=category).order_by('-pk')
  return render(request, 'product/product_list.html', {
    'category': category,
    'product_list': product_list,
    'categories': Category.objects.all(),
    'no_category_post_count': Product.objects.filter(category=None).count(),
    'companies': Company.objects.all()
  })

def company_page(request, slug):
  company = Company.objects.get(slug=slug)
  product_list = Product.objects.filter(company=company).order_by('-pk')
  return render(request, 'product/product_list.html', {
    'company': company,
    'product_list': product_list,
    'categories': Category.objects.all(),
    'no_category_post_count': Product.objects.filter(category=None).count(),
    'companies': Company.objects.all()
  })

def tag_page(request, slug):
  tag = Tag.objects.get(slug=slug)
  product_list = tag.product_set.all().filter(tags=tag).order_by('-pk')
  return render(request, 'product/product_list.html', {
    'tag': tag,
    'product_list': product_list,
    'no_tag_product_count': Product.objects.filter(tags=None).count,
    'categories': Category.objects.all(),
    'no_category_post_count': Product.objects.filter(category=None).count(),
  })

product/templates/product/about.html
{% extends 'product/base.html' %}
{% load humanize %}
{% block main_area %}
{% include 'product/header.html' %}
{% include 'product/sidebar.html' %}
        <h1>About</h1>
{% endblock %}

product/templates/product/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block head_title %}Shop Homepage{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'product/bootstrap-4.5.3-dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen"></link>
        <link href="{% static 'product/css/style.css' %}" rel="stylesheet" type="text/css" media="screen"></link>
        <script src="https://kit.fontawesome.com/637c68a387.js" crossorigin="anonymous"></script>
    </head>
    <body>


        {% include 'product/navbar.html' %}
                {% block main_area %}
                {% endblock %}

        {% include 'product/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <!-- Core theme JS-->
        <script src="{% static 'product/bootstrap-4.5.3-dist/js/bootstrap.bundle.min.js' %}"></script>
        <script>
            $(function () {
                $('[data-toggle="popover"]').popover({
                container: 'section'})
            })
        </script>
        <script>
            $('.popover-dismiss').popover({
                trigger: 'focus'
                container: 'section'
            })
        </script>
    </body>
</html>

product/templates/product/company_card.html
<div class="card mb-5">
    <div class="card-body row align-items-center">
        <div class="col-5 col-md-4 p-xs-3 p-sm-3 align-items-center">
            {% if company.company_image %}
            <img class="card-img mb-md-0 rounded" src="{{company.company_image.url}}" alt="{{company}}의 company_image"/>
            {% else %}
            <img class="card-img mb-md-0 rounded" src="https://dummyimage.com/200x200/bdbdbd/ffffff" alt="..." />
            {% endif %}
        </div>
        <div class="col-7 col-md-8">
            <h6><a href="{{product.category.get_absolute_url}}" class="text-reset text-decoration-none mb-0">
                {{company.name|upper}}
            </a></h6>
            <div class="small mb-1"><a href="{{product.company.get_absolute_url}}" class="text-reset text-decoration-none">
                {{company.address}}</a></div>
            <h6 class="text-muted"><small><mark>{{company.contact}}</mark></small></h6>
            <div class="fs-5">
                <span class="d-none d-md-block">{{company.description}}</span>
                <span class="d-md-none small">{{company.description | truncatechars:70 }}</span>
            </div>
            {% if product.tags.exists %}
            <div class="mb-2">
                <i class="fas fa-tag" style="color:#0d6efd"></i>
                {% for t in product.tags.iterator %}
                <span class="badge badge-pill badge-light">
                    <a href="{{t.get_absolute_url}}">{{t}}</a>
                </span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
<div class="d-block m-3"><br></div>

product/templates/product/footer.html
{% load static %}
<!-- Footer-->
        <footer class="bg-img">
            <img class="bg-img position-absolute" src="{% static 'product/image/footer_image.jpeg' %}"
             style="width: 100%; height: 225px; object-fit: cover; object-position: 0 100%;">
            <div class="pt-5 pt-1">
            <div class="container w-50 w-xs-100 vertical-center">
                <dl class="row text-white px-5">
                    <dt class="col-lg-5 pl-lg-5 col-sm-4">주소</dt>
                    <dd class="col-lg-7 col-sm-8">서울특별시 도봉구 쌍문1동 삼양로144길 33</dd>
                    <dt class="col-lg-5 pl-lg-5 col-sm-4">전화번호</dt>
                    <dd class="col-lg-7 col-sm-8">02-901-8000</dd>
                </dl>
            </div>
            <div class="d-none d-md-block w-100 vertical-center">
                <dl class="row text-white px-5">
                    <dt></dt>
                    <dd class="mt-2 col text-center">Copyright &copy; 덕성여자대학교 인터넷프로그래밍 2022</dd>
                </dl>
            </div>
<!--        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>-->
        </div>
        </footer>

product/templates/product/header.html
{% load static %}
<!-- Header-->
        <header class="bg-image" style="height: 350px">
            <div class="container">
                <div class="container mt-5 pt-5 text-center text-white position-absolute"
                style="width: 100%; height: 350px">
                    <p></p>
                    {% if category %}
                    <h1 class="display-4 fw-bolder">Shop in {{category}}</h1>
                    <p class="lead fw-normal text-white-50 mb-0">{{category}}에 포함된 상품들 입니다.</p>
                    {% elif popular_items.exists %}
                    <h1 class="display-4 fw-bolder">Shop in Popular Items</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Popular Items</p>
                    {% elif new_items.exists %}
                    <h1 class="display-4 fw-bolder">Shop in New Arrivals</h1>
                    <p class="lead fw-normal text-white-50 mb-0">New Arrivals</p>
                    {% elif tag %}
                    <h1 class="display-4 fw-bolder">Shop in Tag</h1>
                    <p class="lead fw-normal text-white-50 mb-0">{{tag}} 태그와 관련된 상품들 입니다.</p>
                    {% elif company %}
                    <h1 class="display-4 fw-bolder">Shop in {{company}}</h1>
                    <p class="lead fw-normal text-white-50 mb-0">{{company}}가 제공하는 {{company.product_set.count}}개의 상품이 있습니다.</p>
                    {% else %}
                    <h1 class="display-4 fw-bolder">{% block head_title %}Shop in Product{% endblock %}</h1>
                    <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
                    {% endif %}
                </div>
            </div>
            <img class="bg-image h-100" src="{% static 'product/image/header_image.jpeg' %}"
             style="width: 100%; object-fit: cover; object-position: 0 20%;">
        </header>

product/templates/product/navbar.html
<!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow rounded">
            <div class="container px-4 px-lg-5 mr-auto">
                <a class="navbar-brand" href="/product/"><small><small>Market</small></small> Avocadomato</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="/product/about/">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="/product/">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="/product/popular_items/">Popular Items</a></li>
                                <li><a class="dropdown-item" href="/product/new_arrivals/">New Arrivals</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-expanded="false">제조사</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                {% for c in companies %}
                                <li><a class="dropdown-item" href="{{c.get_absolute_url}}">{{c}}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                      <ul class="navbar-nav ml-auto">
                          {% include 'product/superuser_nav_items.html' %}
                      <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#signInModal">
                            Sign in
                        </a>
                      </li>
                    </ul>
                    <form class="d-flex ml-1 float-sm-right">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>

                </div>
            </div>
        </nav>
<!-- Modal-->
        <div class="modal fade" id="signInModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h6 class="modal-title" id="exampleModalLabel"><i class="fa-solid fa-right-to-bracket"></i> Sign in</h6>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="row">
                      <div class="col">
                          <button type="button" class="btn btn-light btn-block btn-sm"><i class="fa-brands fa-google"></i> Sign in with Google</button>
                          <button type="button" class="btn btn-light btn-block btn-sm"><i class="fa-solid fa-envelope"></i> Sign in with Email</button>
                          <p class="text-center my-3" style="width: 100%; text-align: center; border-bottom: 0.5px solid; line-height: 0.1em;">
                            <small class="font-weight-lighter" style="background:#fff; padding:0 10px;">or</small>
                          </p>
                          <button type="button" class="btn btn-light btn-block btn-sm"><i class="fa-solid fa-envelope"></i> Sign up with Email</button>
                      </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-light btn-sm m-0" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

product/templates/product/product_form.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
  Add New Product
{% endblock %}
{% block main_area %}
{% include 'product/header.html' %}
  <h1>Add New Product</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form | crispy}}
          <div id="div_id_tags_str">
              <label for="id_tags">Tags:</label>
              <input type="text" id="id_tags" name="tags_str"
                  class="textinput textInput form-control">
          </div>
      <button type="submit" class="btn btn-primary float-right mb-1">Submit</button>
  </form>
{% endblock %}

product/templates/product/product_update_form.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
  Add New Product
{% endblock %}
{% block main_area %}
{% include 'product/header.html' %}
  <h1>Add New Product</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form | crispy}}
    <div id="div_id_tags_str">
      <label for="id_tags">New Tags: </label>
      <input type="text" id="id_tags" name="tags_str" value="{{tags_str_default}}"
             class="textinput textInput form-control">
    </div>
    <button type="submit" class="btn btn-primary mb-1">Submit</button>
  </form>
{% endblock %}

product/templates/product/sidebar.html
<div class="d-none d-lg-block">
    <!-- CategoryNav -->
    <nav class="navbar navbar-expand-lg navbar-light justify-content-center p-0 m-0 shadow bg-white" id="CategoryNav">
    <a class="navbar-brand mb-1">Category</a>
    <ul class="navbar-nav">
        {% for c in categories %}
        <li class="nav-item align-middle">
            <a class="nav-link" id="category_item" href="{{c.get_absolute_url}}">
                {{c}}<span class="badge badge-light">{{c.product_set.count}}</span>
            </a>
        </li>
        {% endfor %}
        {% if no_category_post_count %}
        <li class="nav-item align-middle">
            <a class="nav-link" href="product/category/no_category/">
                미분류<span class="badge badge-light">{{no_category_post_count}}</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
</div>

<div class="d-lg-none">
    <!-- CategoryNav -->
    <nav class="navbar navbar-light justify-content-center p-0 m-0 shadow bg-white">
    <a class="navbar-brand mb-1 mx-auto" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
       aria-expanded="false" aria-label="Toggle navigation" style="text-align: center;">
        Category</a>
    <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav" style="text-align: center;">
        {% for c in categories %}
        <li class="nav-item align-middle">
            <a class="nav-link" href="{{c.get_absolute_url}}">
                {{c}}<span class="badge badge-light">{{c.product_set.count}}</span>
            </a>
        </li>
        {% endfor %}
        {% if no_category_post_count %}
        <li class="nav-item align-middle">
            <a class="nav-link" href="product/category/no_category/">
                분류되지 않은 카테고리<span class="badge badge-light">{{no_category_post_count}}</span>
            </a>
        </li>
        {% endif %}
    </ul>
    </div>
    </nav>
</div>

product/templates/product/superuser_adder_productlist.html
    <div class="col mb-5">
        <div class="card h-100 border-primary">
            <a href="/product/create_product/" class="text-decoration-none">
                <img class="card-img-top" src="https://dummyimage.com/450x450/dee2e6/6c757d.jpg" alt="..." />
            </a>
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <a href="/product/create_product/" class="text-decoration-none">
                        <h4 class="fw-bolder mt-0 mt-lg-5 text-primary">
                            Add New Product
                        </h4>
                    </a>
                    <div class="mt-3">
                        <div class="small text-muted font-weight-light mt-lg-1"><mark>Please inform the logistics as products are ready for orders. Lorem ipsum dolor sit amet,
                            consectetur adipiscing elit.</mark></div>
                    </div>
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-primary mt-auto" href="/product/create_product/"><i class="fa-regular fa-plus text-black mr-1"></i> Add New Product</a></div>
            </div>
        </div>
    </div>

product/templates/product/superuser_nav_items.html
<li class="nav-item"><a class="nav-link" href="/product/create_post/">
    <small class="text-weight-light text-primary mt-2">상품등록</small></a></li>
<li class="nav-item"><a class="nav-link" href="/product/create_post/">
    <small class="text-weight-light text-primary mt-2">상품수정</small></a></li>
<li class="nav-item"><a class="nav-link" href="/product/about/">내 페이지</a></li>